services:
  proxy:
    container_name: proxy
    hostname: proxy
    image: nginx:alpine
    restart: always
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      # - "127.0.0.1:3306:3306"

    environment:
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      WEB_BASE_URL: ${WEB_BASE_URL:-http://localhost:3001}
      PORT: ${PORT:-3000}
      WEB_PORT: ${WEB_PORT:-3001}

    #depends_on:
      #- database
      #- api
      #- web

networks:
  bridge:
    name: notes        