services:
  jest:
    image: yousrar/notes_manager:latest
    container_name: jest
    hostname: jest
    command: jest
    build: 
      dockerfile: ./docker/Dockerfile-notes-manager
      context: ../
    volumes:
      - ../api:/api
      # - ../web:/web
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      database:
        condition: service_healthy 

networks:
  bridge:
    name: notes        