services:
  web:
    image: yousrar/notes_manager:latest
    container_name: web
    hostname: web
    command: npm --prefix web start
    build: 
      dockerfile: ./docker/Dockerfile-notes-manager
      context: ../
    volumes:
      # - ./api:/api
      - ../web:/web
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_BASE_URL: ${API_BASE_URL}
    #depends_on:
      #jest:
        #condition: service_completed_successfully
volumes:
  volume_mysql:
networks:
  bridge:
    name: notes